version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - Development
  - Beta-releases
skip_tags: true
build_script:
- sh: mkdir bin ; cd bin ; meson .. ; ninja
test: off
deploy: off
on_finish:
- sh: cd ../.. ; rm -rf Twitchbot